### ISSUE TITLE
yarn run build failed

### ISSUE THREAD

**Issue by shroo-paulli** [cspotcode/cloudformation-declarations#3]
10-10-10-226:cloudformation-typescript-declarations pongli$ yarn run build
yarn run v1.3.2
$ pwsh -NoProfile -ExecutionPolicy RemoteSigned -File ./scripts/npm-run.ps1
{ Error: ENOENT: no such file or directory, open 'cache/html-docs.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readFile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/utils.ts:90:15)
    at Object.readJsonFile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/utils.ts:94:23)
    at /Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:39:25
    at Generator.next (<anonymous>)
    at /Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/tslib/tslib.js:103:16)
    at main (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:17:20)
    at Object.<anonymous> (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:273:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'cache/html-docs.json' }
src/generator/index.ts(25,17): error TS7006: Parameter 'v' implicitly has an 'any' type.
src/generator/index.ts(25,20): error TS7006: Parameter 'k' implicitly has an 'any' type.
src/generator/index.ts(28,20): error TS7006: Parameter 'k' implicitly has an 'any' type.
src/generator/index.ts(28,23): error TS7006: Parameter 'ck' implicitly has an 'any' type.
src/generator/index.ts(91,70): error TS2345: Argument of type 'string | SpecType' is not assignable to parameter of type 'SpecType'.
  Type 'string' is not assignable to type 'SpecType'.
src/generator/index.ts(231,5): error TS2564: Property '_parent' has no initializer and is not definitely assigned in the constructor.
✨  Done in 5.91s.

**Comment by shroo-paulli** [comment]
Hi, is there any update on this issue?
